In [1]:
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

c:\Users\a812616\AgenticAI\Agentic RAG\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model = SentenceTransformer("facebook-dpr-question_encoder-single-nq-base")
#a pretrained Dense Passage Retrieval (DPR) model from HuggingFace

Define Knowledge Base

In [3]:
passages = [
    "The capital of France is Paris.",
    "The heart pumps blood throughout the body.",
    "Transformers are neural network architectures designed for sequence modeling."
]

Encode Passages

In [4]:
#convert textual passages into vector embeddings for similarity search
passage_embeddings = model.encode(passages, convert_to_numpy = True, normalize_embeddings = True)
passage_embeddings.shape

(3, 768)

Build Faiss Index

In [5]:
#Create an index for fast similarity search using inner product(cosine distance after normalization)
dim = passage_embeddings.shape[1]
index = faiss.IndexFlatIP(dim)
index.add(passage_embeddings)

In [6]:
dim

768

Encode Query

In [7]:
#convert user query into the same embedding space as the passages
query = "What is the capital of France?"
query_embedding = model.encode([query], convert_to_numpy=True, normalize_embeddings=True)

In [8]:
len(query_embedding[0])

768

Search Top-K similar passages

In [ ]:
#Retrieve the most relevant passages for the query
k = 2
D, I = index.search(query_embedding, k)
#searching for top 2 records from the already created index

In [10]:
D, I

(array([[0.94370985, 0.6690466 ]], dtype=float32), array([[0, 1]]))

In [ ]:
D[0][0] #matching score for the first document is .94

np.float32(0.94370985)

Display Results

In [12]:
print("Query:", query)
for rank, idx in enumerate(I[0]):
    print(f"Rank {rank+1}: {passages[idx]} (score = {D[0][rank]:.4f})")

Query: What is the capital of France?
Rank 1: The capital of France is Paris. (score = 0.9437)
Rank 2: The heart pumps blood throughout the body. (score = 0.6690)


In [13]:
I[0]

array([0, 1])

In [14]:
D[0]

array([0.94370985, 0.6690466 ], dtype=float32)